
package view.gui;

import ficheros.ClassFichero;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
import model.exceptions.FormatException;
import model.exceptions.InvalidDataException;
import model.validations.UserDataValidations;

/**
 *
 * @author erikbercam
 */
public class JFrameMain extends javax.swing.JFrame {

    public JFrameMain() {
        initComponents();
        initConfig();
        this.setLocationRelativeTo(null);
    }

      private void initConfig() {
        jButtonValidate.setEnabled(true);
        jButtonClear.setEnabled(true);
        jButtonCSV.setEnabled(false);
        jTextFieldNombre.setText("");
        jTextFieldNIF.setText("");
        jTextFieldEmail.setText("");
        jTextFieldBirthday.setText("");
        jTextFieldZIP.setText("");

        jLabelErrorName.setText("");
        jLabelErrorNIF.setText("");
        jLabelErrorEmail.setText("");
        jLabelErrorBirthday.setText("");
        jLabelErrorZIP.setText("");

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNIF = new javax.swing.JLabel();
        jTextFieldNIF = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelBirthday = new javax.swing.JLabel();
        jTextFieldBirthday = new javax.swing.JTextField();
        jLabelAge = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jLabelZIP = new javax.swing.JLabel();
        jTextFieldZIP = new javax.swing.JTextField();
        jButtonValidate = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonCSV = new javax.swing.JButton();
        Monlau = new javax.swing.JLabel();
        jLabelErrorName = new javax.swing.JLabel();
        jLabelErrorNIF = new javax.swing.JLabel();
        jLabelErrorEmail = new javax.swing.JLabel();
        jLabelErrorBirthday = new javax.swing.JLabel();
        jLabelErrorAge = new javax.swing.JLabel();
        jLabelErrorZIP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTitulo.setText("VALIDAR DATOS DE USUARIO");

        jLabelName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelName.setText("Name:");
        jLabelName.setToolTipText("");

        jLabelNIF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNIF.setText("NIF:");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEmail.setText("Email:");

        jLabelBirthday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelBirthday.setText("Birthday:");
        jLabelBirthday.setToolTipText("");

        jTextFieldBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBirthdayActionPerformed(evt);
            }
        });

        jLabelAge.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAge.setText("Age:");

        jLabelZIP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelZIP.setText("ZIP:");

        jTextFieldZIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldZIPActionPerformed(evt);
            }
        });

        jButtonValidate.setBackground(new java.awt.Color(0, 0, 0));
        jButtonValidate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonValidate.setForeground(new java.awt.Color(255, 255, 0));
        jButtonValidate.setText("Validate");
        jButtonValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidateActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(0, 0, 0));
        jButtonClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 0));
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonCSV.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCSV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCSV.setForeground(new java.awt.Color(255, 255, 0));
        jButtonCSV.setText("CSV");
        jButtonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSVActionPerformed(evt);
            }
        });

        Monlau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Logo.png"))); // NOI18N

        jLabelErrorName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelErrorName.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrorNIF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelErrorNIF.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrorEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelErrorEmail.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrorBirthday.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelErrorBirthday.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrorAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelErrorAge.setForeground(new java.awt.Color(255, 0, 0));

        jLabelErrorZIP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelErrorZIP.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonValidate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClear)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCSV))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelName)
                                    .addComponent(jLabelNIF)
                                    .addComponent(jLabelEmail))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNombre)
                                    .addComponent(jTextFieldNIF)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelBirthday)
                                    .addComponent(jLabelAge)
                                    .addComponent(jLabelZIP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAge)
                                    .addComponent(jTextFieldZIP))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelErrorName, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jLabelErrorNIF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErrorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErrorBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErrorAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelErrorZIP, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addGap(48, 48, 48))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(Monlau)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Monlau)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorName))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNIF)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelErrorNIF)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelErrorEmail))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBirthday)
                    .addComponent(jTextFieldBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorBirthday))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAge)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorAge))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZIP)
                    .addComponent(jTextFieldZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorZIP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValidate)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonCSV))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBirthdayActionPerformed

    }//GEN-LAST:event_jTextFieldBirthdayActionPerformed

    private void jTextFieldZIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldZIPActionPerformed

    }//GEN-LAST:event_jTextFieldZIPActionPerformed

    private void jButtonValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidateActionPerformed
             boolean isValid = true;
        String name = jTextFieldNombre.getText();
        try {
            UserDataValidations.checkName(name);
            jLabelErrorName.setText("");
        } catch (FormatException e) {
            jLabelErrorName.setText(e.getMessage());
            isValid = false;
        }


         String nif = jTextFieldNIF.getText();
        try {
            UserDataValidations.checkID(1, nif);
            jLabelErrorNIF.setText("");
        } catch (FormatException | InvalidDataException e) {
            jLabelErrorNIF.setText(e.getMessage());
            isValid = false;
        }

        String email = jTextFieldEmail.getText();
        try {
            UserDataValidations.checkEmail(email);
            jLabelErrorEmail.setText("");
        } catch (FormatException e) {
            jLabelErrorEmail.setText(e.getMessage());
            isValid = false;
        }

        String birthday = jTextFieldBirthday.getText();
        try {
            UserDataValidations.checkFormatDate(birthday);
            jLabelErrorBirthday.setText("");
        } catch (FormatException e) {
            jLabelErrorBirthday.setText(e.getMessage());
            isValid = false;
        }

        String age = jTextFieldAge.getText();
        try {
            if (age == null || age.isEmpty()) {
                jLabelErrorAge.setText("La edad no puede estar vacía");
                isValid = false;
                return;
            }

             UserDataValidations.isNumeric(age);
            int ageValue = Integer.parseInt(age);
            int calculatedAge = UserDataValidations.checkCalculateDate(birthday);
            
            if (ageValue != calculatedAge) {
                jLabelErrorAge.setText("La edad no coincide con la fecha de nacimiento");
                isValid = false;
            } else {
                jLabelErrorAge.setText("");
            }
        } catch (FormatException e) {
            jLabelErrorAge.setText(e.getMessage());
            isValid = false;
        }

        String zip = jTextFieldZIP.getText();
        try {
            UserDataValidations.checkPostalCode(zip);
            jLabelErrorZIP.setText("");
        } catch (FormatException e) {
            jLabelErrorZIP.setText(e.getMessage());
            isValid = false;
        }

        if (isValid) {
            jTextFieldNombre.setEditable(false);
            jTextFieldNIF.setEditable(false);
            jTextFieldEmail.setEditable(false);
            jTextFieldBirthday.setEditable(false);
            jTextFieldAge.setEditable(false);
            jTextFieldZIP.setEditable(false);

            jButtonValidate.setEnabled(false);
            jButtonCSV.setEnabled(true);
        }

    }//GEN-LAST:event_jButtonValidateActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed

        jTextFieldNombre.setText("");
        jTextFieldNIF.setText("");
        jTextFieldEmail.setText("");
        jTextFieldBirthday.setText("");
        jTextFieldAge.setText("");
        jTextFieldZIP.setText("");

        jLabelErrorName.setText("");
        jLabelErrorNIF.setText("");
        jLabelErrorEmail.setText("");
        jLabelErrorBirthday.setText("");
        jLabelErrorAge.setText("");
        jLabelErrorZIP.setText("");

        jTextFieldNombre.setEditable(true);
        jTextFieldNIF.setEditable(true);
        jTextFieldEmail.setEditable(true);
        jTextFieldBirthday.setEditable(true);
        jTextFieldAge.setEditable(true);
        jTextFieldZIP.setEditable(true);

        jButtonValidate.setEnabled(true);
        jButtonCSV.setEnabled(false);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSVActionPerformed

        String nombre = jTextFieldNombre.getText();
        String nif = jTextFieldNIF.getText();
        String email = jTextFieldEmail.getText();
        String birthday = jTextFieldBirthday.getText();
        String zip = jTextFieldZIP.getText();

        String line = nombre + ";" + nif + ";" + email + ";" + birthday + ";" + zip + "\n";

        ClassFichero.writeFile(line);

        String confirmationMessage = "Usuario registrado correctamente\n";
        ClassFichero.writeFile(confirmationMessage);

        JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");

        jButtonCSV.setEnabled(false);
    }//GEN-LAST:event_jButtonCSVActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(String args[]) throws FileNotFoundException {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameMain().setVisible(true);
        });
        ClassFichero.createFile("user_data_EBC.csv");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Monlau;
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonValidate;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelBirthday;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelErrorAge;
    private javax.swing.JLabel jLabelErrorBirthday;
    private javax.swing.JLabel jLabelErrorEmail;
    private javax.swing.JLabel jLabelErrorNIF;
    private javax.swing.JLabel jLabelErrorName;
    private javax.swing.JLabel jLabelErrorZIP;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelZIP;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldBirthday;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldZIP;
    // End of variables declaration//GEN-END:variables
}
